[project]
name = "hexlet-flask-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=33.3.1",
    "flask>=3.1.0",
    "flask-wtf>=1.2.2",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.3",
]



[dependency-groups]
dev = [
    "pytest>=8.3.4",
]